name: shell commands

on:
  push:

jobs:
  runs-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3 
      - name: echo string
        run: echo "Hello World i'm blessed"
      - name: multi string
        run: |
          node -v
          npm -v
